version: '3.3'

services:
  db:
    image: 'postgres:14.2-alpine'
    restart: always
    ports:
      - ${FORWARD_DB_PORT:-5432}:5432
    environment:
      PGPASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - 'economics-db:/var/lib/postgresql/data'
    networks:
      - economics-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
      retries: 3
      timeout: 5s

networks:
  economics-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.12.0/24
    driver_opts:
      com.docker.network.bridge.name: eco-100

volumes:
  economics-db:
    driver: local
